-- AlterTable
ALTER TABLE "public"."User" ADD COLUMN     "CL" INTEGER NOT NULL DEFAULT 6,
ADD COLUMN     "EL" INTEGER NOT NULL DEFAULT 12,
ADD COLUMN     "ML" INTEGER NOT NULL DEFAULT 180,
ADD COLUMN     "SL" INTEGER NOT NULL DEFAULT 6;
